function Hd = F3_LowPass_200
%F3_LOWPASS_200 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 20-Feb-2026 15:26:28

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 4000;  % Sampling Frequency

N  = 10;   % Order
Fc = 250;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
