function Hd = F7_BandPass_250_350
%F7_BANDPASS_250_350 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 20-Feb-2026 15:31:54

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 4000;  % Sampling Frequency

N   = 10;   % Order
Fc1 = 150;  % First Cutoff Frequency
Fc2 = 350;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
