function Hd = F9_BandStop_150_350
%F9_BANDSTOP_200_300 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
% Generated on: 20-Feb-2026 15:34:13

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 4000;  % Sampling Frequency

N   = 10;   % Order
Fc1 = 150;  % First Cutoff Frequency
Fc2 = 350;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
